### PR TITLE
Adds a Python introductory vignette

### LINKED ISSUE #146: Create a single intro Vignette
It would be important to have a single intro Vignette for both Python and R, or at least a Vignette  that is very similar in both languages.  This is the current [intro Vignette in R](https://cran.r-project.org/web/packages/geobr/vignettes/intro_to_geobr.html). I

### PR DESCRIPTION
**Pull request by jvfe**
Closes #146 

Changes made:

* Added a [python jupyter notebook](https://github.com/jvfe/geobr/blob/docs/py-vignette/python-package/examples/1.%20intro-to-geobr.ipynb) with the same text and code examples as the [R package vignette](https://cran.r-project.org/web/packages/geobr/vignettes/intro_to_geobr.html).
* Renames the files in the examples directory to reflect the new order (Let me know if this is not necessary and I'll revert it)

Some notes:

* I think the only real code difference between the two tutorials is that I ommitted this line:
```R
meso <- read_intermediate_region(year=2017)
```
As I don't think there's a python equivalent for this function yet. The rest of the examples remain the same.

### CODE REVIEW

**Comment by rafapereirabr** [comment]
Thanks, @jvfe .  @JoaoCarabetta , could please asses this?

**Comment by JoaoCarabetta** [comment]
Looks great! 

@jvfe , thanks for the contribution :)

@rafapereirabr, I was wondering on how to add it to the documentation? Should we export a html version of it?

**Comment by rafapereirabr** [comment]
I'm not familiar with wheter Python libraries have vignettes and, if so, how they are handled. In any case, a html version of the vignette would suffice. We can probably embed the html vignettes on the `geobr`webpage.

**Comment by jvfe** [comment]
> I'm not familiar with wheter Python libraries have vignettes and, if so, how they are handled. In any case, a html version of the vignette would suffice. We can probably embed the html vignettes on the `geobr`webpage.

I don't believe there's an R-vignette equivalent for Python packages, embedding the html vignette on the webpage seems like a simple solution, but I don't know enough packagedown/rmarkdown for how to do that :P 

But, I think that just having the introductory vignette as a jupyter notebook like the other tutorials would be simple enough for now.

**Comment by JoaoCarabetta** [comment]
Let's export a html version as well. @rafapereirabr can decide later whether to add it to the documentation.

**Comment by jvfe** [comment]
> Let's export a html version as well. @rafapereirabr can decide later whether to add it to the documentation.

Done!

**Comment by rafapereirabr** [comment]
Thanks. The next step is to understand how we can present the `html` file as a vignette in the "Articles" section of our [pkgdown website](https://ipeagit.github.io/geobr/). There might be some useful info about this [here ](https://pkgdown.r-lib.org/articles/pkgdown.html) or [here](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/). If someone could look into this it would be great. Otherwise, I try to address this in sometime in December

**Comment by jvfe** [comment]
Hi, sorry for taking this long, got carried away by work. 

So, this was harder than I anticipated, and I couldn't figure out how to include the html file itself on the pkgdown build cycle, so, following your advice, here's what I did [on another branch of my repo](https://github.com/jvfe/geobr/tree/docs/py-in-pkgdown):

* Converted the jupyter notebook to a markdown file. Edited this markdown file to be similar to an Rmarkdown file.

* Moved the Rmarkdown python vignette to a subdirectory of the vignettes/ directory in the r-package, so it gets built when building the site but is not included in the final package, as [explained in one of the links you sent](https://pkgdown.r-lib.org/articles/pkgdown.html#articles)

* Updated the website (`build_site()`), now it includes another page under the articles tab corresponding to the python vignette.

If you think that works for you, just say so and I can merge that branch into this pull requests branch and that's it!

Thanks for the advice.

**Comment by rafapereirabr** [comment]
Hi @jvfe . Thanks for looking into this. I've tested building the pkgdown website with your branch and it seems to be workig fine without compromising the R package. Please go ahead with merging your branch in this pull request. Thanks for your effort and patience.

**Comment by jvfe** [comment]
> Hi @jvfe . Thanks for looking into this. I've tested building the pkgdown website with your branch and it seems to be workig fine without compromising the R package. Please go ahead with merging your branch in this pull request. Thanks for your effort and patience.

Done! Thanks for the help.

**Comment by rafapereirabr** [comment]
Thanks, @jvfe . The website has been updated with the new intro vignette to the Python version of geobr https://ipeagit.github.io/geobr/articles/python-intro/py-intro-to-geobr.html

**Pull request merged**
