### PR TITLE
[still incomplete]

### PR DESCRIPTION
**Pull request by felipegermanos**
- New function in 'utils' to check year
- One minor correction from 'actiave' to 'activate'
- Add pandas to requirements
- New function to select biomes

### CODE REVIEW

**Comment by rafapereirabr** [comment]
Hi @felipegermanos, thank you for the PR. We still need to fix a couple things internally regarding the organization of the Python version of `geobr` before we start creating / translating the other functions in the package. After we fix this, I will start creating an `issue` for each function in the package.

**Comment by JoaoCarabetta** [comment]
Hi @rafapereirabr, I coded that with him this weekend. Today and tomorrow, I am going to build the first python functions and I will be using the function that @felipegermanos wrote, that is why I asked him to do this PR.

So, just keep this PR open that I will finish it. Thanks :)

**Comment by JoaoCarabetta** [comment]
@rafapereirabr, you can close this issue. The code was replicated in a different PR, #98. Thanks

**Comment by rafapereirabr** [comment]
Ok. Closing it now.

**Pull request closed without merging**
