### PR TITLE
typo Pernanbuco -> Pernambuco

### PR DESCRIPTION
**Pull request by jtrecenti**
Small typo 

typo Pernanbuco -> Pernambuco

updated `prep_data` script and `.RData` resulting from it.

### CODE REVIEW

**Comment by rafapereirabr** [comment]
Hi Julio. Thank you for the contribution in fixing the typos. I would be glad to update the `prep_` script. Mind you, however, that we do not upload `.RData` files to the github repository. Could you please remove the `.RData` from the Pull Request?

**Comment by jtrecenti** [comment]
thanks! deleted the file

**Comment by rafapereirabr** [comment]
Thanks!

**Comment by rafapereirabr** [comment]
I've updated the `grid_state_correspondence_table` in the development version of the package on github. This should be published in the next update of `geobr` on CRAN.

**Pull request merged**
