### PR TITLE
Fix not reaching download mirror #312

### PR DESCRIPTION
**Pull request by vss-2**

### CODE REVIEW

**Comment by rafapereirabr** [comment]
Hi @vss-2 , could you please check why this PR is not passing package tests?

**Comment by vss-2** [comment]
Hello, I'm closing and opening this PR to trigger a re-run of tests.
I suspect the previous run failed due to a config issue at that point.
If not, please disregard this comment.

**Comment by vss-2** [comment]
Checking out: it seems I've forgotten to add `pull_request` triggers on line 1 of [Python-CMD-check](https://github.com/ipeaGIT/geobr/blob/master/.github/workflows/Python-CMD-check.yaml). To make Python GHA package-testing equals to [R](https://github.com/ipeaGIT/geobr/blob/master/.github/workflows/R-CMD-check.yaml) the first line should be replaced to something like:
```yaml
on:
  push:
    paths:
      - python-package/**
    branches:
      - main
      - master
      - dev
  pull_request:
    paths:
      - python-package/**
    branches:
      - main
      - master
      - dev
```
Also,
I've scrolled entirely [AppVeyor history](https://ci.appveyor.com/project/rafapereirabr/geobr/history) and I couldn't find a successful build in the past four years. 
It seems AppVeyor notifications aren't providing useful statuses anymore.

**Comment by rafapereirabr** [comment]
Ok, would you like to add pull_request triggers to Python-CMD-check first?

**Comment by vss-2** [comment]
Just to make sure this PR will try to reach the download mirrors, I will include the pull_request code first. Next, if the GHA doesn't trigger automatically, I will re-run this PR.

**Comment by rafapereirabr** [comment]
thanks !

**Pull request merged**
